export const VideoJson = [
    {
        id: 1,
        videoId: "Ndz3PYADcvA",
        title: "How  Engineers Can Build PERMANENT Job Security in 2025",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        thumbnail: "https://i.ytimg.com/vi/Ndz3PYADcvA/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDGEGJ_dxEQj8jz68y0-wb_GVNg4g",
        url: "https://www.youtube.com/watch?v=Ndz3PYADcvA",
        profile: "https://yt3.ggpht.com/0wMhEQe-e_FLwpQgUjDa82CbWVH6IplMb2Z8-JC_ysJ4aIy0d4cLzdd2omFnxEzPoe31ICio=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 1",
        channelId: "@channel1",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: '1000',
        duration: "10:00",
        publishedAt: "2025-05-10",
        subscriberCount: 10000,
        category: ["Education", "Technology"]
    },
    {
        id: 2,
        videoId: "bGnRoVFwUeE",
        title: "Ka Kong Bertina Kam Donkam Khuslai Ban Ïoh Pyndep PhD | Mang U CM 1.35 Lak Na CMSG",
        description: "Description for Video 2",
        thumbnail: "https://i.ytimg.com/vi/bGnRoVFwUeE/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCF2Kp2YFNuCp2eRdpMRUs1pbTAag",
        url: "https://www.youtube.com/watch?v=bGnRoVFwUeE",
        profile: "https://yt3.ggpht.com/uzqjVPREImGM9v8N63I6sgpByD7WfVTBR6e4UKPrhEXLXGBB9dzOWHeLd30Ip2o4JQ96P22Tp2o=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 2",
        channelId: "@channel2",
        banner: "https://yt3.googleusercontent.com/nJq0oT-z_xp-jouZtYoB0infUw--UBI1aSnWMGAgLIFjZauT7MOctf92GQDy5NYlRkBfiuQpRR4=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
        views: 24000000,
        duration: "20:00",
        publishedAt: "2023-02-01",
        subscriberCount: 2000000,
        category: ["Education", "News"]
    },
    {
        id: 3,
        videoId: "X3yATXAWL_g",
        title: "200W Camping Power Station 192Wh Power Bank 60000mAh LiFePo4",
        description: "Description for Video 3",
        thumbnail: "https://i.ytimg.com/vi/X3yATXAWL_g/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBDEpQpfSZda3ysTuYJYdatZ1wcRQ",
        url: "https://www.youtube.com/watch?v=X3yATXAWL_g",
        profile: "https://yt3.ggpht.com/0CuJkUiY3A3XobJeYDDSeZInfMUyW2o01cw5PZn1gRN9y33D_pFW_i0CysAbaNMPv28a0FQ2=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 3",
        channelId: "@channel3",
        banner: "https://yt3.googleusercontent.com/arZJtHohCISyz3BrZA0ynNAM7rivDCBNwsDPtFI7p6SYswq5Tjhm783nGh1TOX4m4ksEV2sJ=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
        views: 3000,
        duration: "30:00",
        publishedAt: "2023-03-01",
        subscriberCount: 99,
        category: ["Technology", "Gadgets"]
    },
    {
        id: 4,
        videoId: "TQdLgzVk2T8",
        title: "The Beginner's Guide to Clean Architecture",
        description: "Description for Video 4",
        thumbnail: "https://i.ytimg.com/vi/TQdLgzVk2T8/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLC383Mm6ytkTCIhNNt3yPRn-sVWIg",
        url: "https://www.youtube.com/watch?v=TQdLgzVk2T8",
        profile: "https://yt3.ggpht.com/E_K5727J3QuOP20WbsepnNRkiyb8CFdj2xu_WCA7NL717A356D2VpPGjH_n6BXPtumyKuEFvjA=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 4",
        channelId: "@channel4",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: 4000,
        duration: "40:00",
        publishedAt: "2023-04-01",
        subscriberCount: 2000,
        category: ["Education", "Programming"]
    },
    {
        id: 5,
        videoId: "rl5mkbx9yNU",
        title: "𝙿𝚊𝚠𝚗𝚊𝚖 𝚔𝚒 𝚔𝚑𝚢𝚗𝚗𝚊𝚑 𝚋𝚊 𝚛𝚠𝚊𝚒 𝚁𝚒 𝚕𝚞𝚖 𝚋𝚊𝚍 𝚟𝚊𝚗𝚍𝚎 𝚖𝚊𝚝𝚊𝚛𝚊𝚖  𝙷𝚊 𝚔𝚢𝚕𝚕𝚎𝚗𝚐 𝚔𝚊 𝚙𝚢𝚛𝚝𝚑𝚎𝚒",
        description: "Description for Video 5",
        thumbnail: "https://i.ytimg.com/vi/rl5mkbx9yNU/hq720.jpg?sqp=-oaymwFBCNAFEJQDSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYAC0AWKAgwIABABGEEgZSg4MA8=&rs=AOn4CLAdVMWBOMocZWoKyrNq0Y2d-v0WBw",
        url: "https://www.youtube.com/watch?v=rl5mkbx9yNU",
        profile: "https://yt3.ggpht.com/ZP7yv6nmEtYFpdry-04aUdz72-jQWH8wwkfXpQKNUEKVp4Dml6wV380Sb4N96XYNVvl1vwEMSQ=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 5",
        channelId: "@channel5",
        banner: "https://yt3.googleusercontent.com/nJq0oT-z_xp-jouZtYoB0infUw--UBI1aSnWMGAgLIFjZauT7MOctf92GQDy5NYlRkBfiuQpRR4=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
        views: 5000,
        duration: "50:00",
        publishedAt: "2023-05-01",
        subscriberCount: 999,
        category: ["Entertainment", "Lifestyle", "Music"]
    },
    {
        id: 6,
        videoId: "TWM-atA8ft8",
        title: "Career Podcast || E1 - Content Creator || Code Freemen",
        description: "Description for Video 6",
        thumbnail: "https://i.ytimg.com/vi/TWM-atA8ft8/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBlWXgi3v86mpOgZtOSUyzVeRI20Q",
        url: "https://www.youtube.com/watch?v=TWM-atA8ft8",
        profile: "https://yt3.ggpht.com/kd_wAtpKhygpsXyZHGE5zDz2nM6dZmavS5WtCRHxy6VSZTAQY0UumPRSoZuj6EuYWaYnQ05C=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 6",
        channelId: "@channel6",
        banner: "https://yt3.googleusercontent.com/arZJtHohCISyz3BrZA0ynNAM7rivDCBNwsDPtFI7p6SYswq5Tjhm783nGh1TOX4m4ksEV2sJ=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
        views: 6000,
        duration: "60:00",
        publishedAt: "2023-06-01",
        subscriberCount: 2000000,
        category: ["Podcast", "Career"]
    },
    {
        id: 7,
        videoId: "Ndz3PYADcvA",
        title: "How  Engineers Can Build PERMANENT Job Security in 2025",
        description: "Description for Video 7",
        thumbnail: "https://i.ytimg.com/vi/Ndz3PYADcvA/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDGEGJ_dxEQj8jz68y0-wb_GVNg4g",
        url: "https://www.youtube.com/watch?v=Ndz3PYADcvA",
        profile: "https://yt3.ggpht.com/0wMhEQe-e_FLwpQgUjDa82CbWVH6IplMb2Z8-JC_ysJ4aIy0d4cLzdd2omFnxEzPoe31ICio=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 7",
        channelId: "@channel7",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: 7000,
        duration: "70:00",
        publishedAt: "2023-07-01",
        subscriberCount: 8792,
        category: ["Education", "Technology"]
    },
    {
        id: 8,
        videoId: "bGnRoVFwUeE",
        title: "Ka Kong Bertina Kam Donkam Khuslai Ban Ïoh Pyndep PhD | Mang U CM 1.35 Lak Na CMSG",
        description: "Description for Video 8",
        thumbnail: "https://i.ytimg.com/vi/bGnRoVFwUeE/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCF2Kp2YFNuCp2eRdpMRUs1pbTAag",
        url: "https://www.youtube.com/watch?v=bGnRoVFwUeE",
        profile: "https://yt3.ggpht.com/uzqjVPREImGM9v8N63I6sgpByD7WfVTBR6e4UKPrhEXLXGBB9dzOWHeLd30Ip2o4JQ96P22Tp2o=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 8",
        channelId: "@channel8",
        banner: "https://yt3.googleusercontent.com/nJq0oT-z_xp-jouZtYoB0infUw--UBI1aSnWMGAgLIFjZauT7MOctf92GQDy5NYlRkBfiuQpRR4=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
        views: 8000,
        duration: "80:00",
        publishedAt: "2023-08-01",
        subscriberCount: 8090911,
        category: ["Education", "News"]
    },
    {
        id: 9,
        videoId: "X3yATXAWL_g",
        title: "200W Camping Power Station 192Wh Power Bank 60000mAh LiFePo4",
        description: "Description for Video 9",
        thumbnail: "https://i.ytimg.com/vi/X3yATXAWL_g/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBDEpQpfSZda3ysTuYJYdatZ1wcRQ",
        url: "https://www.youtube.com/watch?v=X3yATXAWL_g",
        profile: "https://yt3.ggpht.com/0CuJkUiY3A3XobJeYDDSeZInfMUyW2o01cw5PZn1gRN9y33D_pFW_i0CysAbaNMPv28a0FQ2=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 9",
        channelId: "@channel9",
        banner: "https://yt3.googleusercontent.com/arZJtHohCISyz3BrZA0ynNAM7rivDCBNwsDPtFI7p6SYswq5Tjhm783nGh1TOX4m4ksEV2sJ=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
        views: 9000,
        duration: "90:00",
        publishedAt: "2023-09-01",
        subscriberCount: 67657,
        category: ["Technology", "Gadgets"]
    },
    {
        id: 10,
        videoId: "TQdLgzVk2T8",
        title: "The Beginner's Guide to Clean Architecture",
        description: "Description for Video 10",
        thumbnail: "https://i.ytimg.com/vi/TQdLgzVk2T8/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLC383Mm6ytkTCIhNNt3yPRn-sVWIg",
        url: "https://www.youtube.com/watch?v=TQdLgzVk2T8",
        profile: "https://yt3.ggpht.com/E_K5727J3QuOP20WbsepnNRkiyb8CFdj2xu_WCA7NL717A356D2VpPGjH_n6BXPtumyKuEFvjA=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 10",
        channelId: "@channel10",
        views: 10000,
        duration: "100:00",
        publishedAt: "2023-10-01",
        subscriberCount: 767112,
        category: ["Education", "Programming"]
    },
    {
        id: 11,
        videoId: "rl5mkbx9yNU",
        title: "𝙿𝚊𝚠𝚗𝚊𝚖 𝚔𝚒 𝚔𝚑𝚢𝚗𝚗𝚊𝚑 𝚋𝚊 𝚛𝚠𝚊𝚒 𝚁𝚒 𝚕𝚞𝚖 𝚋𝚊𝚍 𝚟𝚊𝚗𝚍𝚎 𝚖𝚊𝚝𝚊𝚛𝚊𝚖  𝙷𝚊 𝚔𝚢𝚕𝚕𝚎𝚗𝚐 𝚔𝚊 𝚙𝚢𝚛𝚝𝚑𝚎𝚒",
        description: "Description for Video 11",
        thumbnail: "https://i.ytimg.com/vi/rl5mkbx9yNU/hq720.jpg?sqp=-oaymwFBCNAFEJQDSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYAC0AWKAgwIABABGEEgZSg4MA8=&rs=AOn4CLAdVMWBOMocZWoKyrNq0Y2d-v0WBw",
        url: "https://www.youtube.com/watch?v=rl5mkbx9yNU",
        profile: "https://yt3.ggpht.com/ZP7yv6nmEtYFpdry-04aUdz72-jQWH8wwkfXpQKNUEKVp4Dml6wV380Sb4N96XYNVvl1vwEMSQ=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 11",
        channelId: "@channel11",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: 11000,
        duration: "110:00",
        publishedAt: "2023-11-01",
        subscriberCount: 2000000,
        category: ["Entertainment", "Lifestyle", "Music"]
    },
    {
        id: 12,
        videoId: "TWM-atA8ft8",
        title: "Career Podcast || E1 - Content Creator || Code Freemen",
        description: "Description for Video 12",
        thumbnail: "https://i.ytimg.com/vi/TWM-atA8ft8/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBlWXgi3v86mpOgZtOSUyzVeRI20Q",
        url: "https://www.youtube.com/watch?v=TWM-atA8ft8",
        profile: "https://yt3.ggpht.com/kd_wAtpKhygpsXyZHGE5zDz2nM6dZmavS5WtCRHxy6VSZTAQY0UumPRSoZuj6EuYWaYnQ05C=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 12",
        channelId: "@channel12",
        banner: "https://yt3.googleusercontent.com/nJq0oT-z_xp-jouZtYoB0infUw--UBI1aSnWMGAgLIFjZauT7MOctf92GQDy5NYlRkBfiuQpRR4=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
        views: 12000,
        duration: "120:00",
        publishedAt: "2023-12-01",
        subscriberCount: 9998789,
        category: ["Podcast", "Career"]
    },
    {
        id: 13,
        videoId: "Ndz3PYADcvA",
        title: "How Engineers Can Build PERMANENT Job Security in 2025",
        description: "Description for Video 13",
        thumbnail: "https://i.ytimg.com/vi/Ndz3PYADcvA/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDGEGJ_dxEQj8jz68y0-wb_GVNg4g",
        url: "https://www.youtube.com/watch?v=Ndz3PYADcvA",
        profile: "https://yt3.ggpht.com/0wMhEQe-e_FLwpQgUjDa82CbWVH6IplMb2Z8-JC_ysJ4aIy0d4cLzdd2omFnxEzPoe31ICio=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 13",
        channelId: "@channel13",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: 13000,
        duration: "130:00",
        publishedAt: "2023-01-02",
        subscriberCount: 676567,
        category: ["Education", "Technology"]
    }
]