export const VideoJson = [
    {
        id: 1,
        videoId: "Ndz3PYADcvA",
        title: "How  Engineers Can Build PERMANENT Job Security in 2025",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        thumbnail: "https://i.ytimg.com/vi/Ndz3PYADcvA/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDGEGJ_dxEQj8jz68y0-wb_GVNg4g",
        url: "https://www.youtube.com/watch?v=Ndz3PYADcvA",
        profile: "https://yt3.ggpht.com/0wMhEQe-e_FLwpQgUjDa82CbWVH6IplMb2Z8-JC_ysJ4aIy0d4cLzdd2omFnxEzPoe31ICio=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 1",
        channelId: "@channel1",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: '1000',
        duration: "10:00",
        publishedAt: "2025-05-10",
        subscriberCount: 10000,
        category: ["Education", "Technology"]
    },
    {
        id: 2,
        videoId: "bGnRoVFwUeE",
        title: "Ka Kong Bertina Kam Donkam Khuslai Ban Ïoh Pyndep PhD | Mang U CM 1.35 Lak Na CMSG",
        description: "Description for Video 2",
        thumbnail: "https://i.ytimg.com/vi/bGnRoVFwUeE/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCF2Kp2YFNuCp2eRdpMRUs1pbTAag",
        url: "https://www.youtube.com/watch?v=bGnRoVFwUeE",
        profile: "https://yt3.ggpht.com/uzqjVPREImGM9v8N63I6sgpByD7WfVTBR6e4UKPrhEXLXGBB9dzOWHeLd30Ip2o4JQ96P22Tp2o=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 2",
        channelId: "@channel2",
        banner: "https://yt3.googleusercontent.com/nJq0oT-z_xp-jouZtYoB0infUw--UBI1aSnWMGAgLIFjZauT7MOctf92GQDy5NYlRkBfiuQpRR4=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
        views: 24000000,
        duration: "20:00",
        publishedAt: "2023-02-01",
        subscriberCount: 2000000,
        category: ["Education", "News"]
    },
    {
        id: 3,
        videoId: "X3yATXAWL_g",
        title: "200W Camping Power Station 192Wh Power Bank 60000mAh LiFePo4",
        description: "Description for Video 3",
        thumbnail: "https://i.ytimg.com/vi/X3yATXAWL_g/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBDEpQpfSZda3ysTuYJYdatZ1wcRQ",
        url: "https://www.youtube.com/watch?v=X3yATXAWL_g",
        profile: "https://yt3.ggpht.com/0CuJkUiY3A3XobJeYDDSeZInfMUyW2o01cw5PZn1gRN9y33D_pFW_i0CysAbaNMPv28a0FQ2=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 3",
        channelId: "@channel3",
        banner: "https://yt3.googleusercontent.com/arZJtHohCISyz3BrZA0ynNAM7rivDCBNwsDPtFI7p6SYswq5Tjhm783nGh1TOX4m4ksEV2sJ=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
        views: 3000,
        duration: "30:00",
        publishedAt: "2023-03-01",
        subscriberCount: 99,
        category: ["Technology", "Gadgets"]
    },
    {
        id: 4,
        videoId: "TQdLgzVk2T8",
        title: "The Beginner's Guide to Clean Architecture",
        description: "Description for Video 4",
        thumbnail: "https://i.ytimg.com/vi/TQdLgzVk2T8/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLC383Mm6ytkTCIhNNt3yPRn-sVWIg",
        url: "https://www.youtube.com/watch?v=TQdLgzVk2T8",
        profile: "https://yt3.ggpht.com/E_K5727J3QuOP20WbsepnNRkiyb8CFdj2xu_WCA7NL717A356D2VpPGjH_n6BXPtumyKuEFvjA=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 4",
        channelId: "@channel4",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: 4000,
        duration: "40:00",
        publishedAt: "2023-04-01",
        subscriberCount: 2000,
        category: ["Education", "Programming"]
    },
    {
        id: 5,
        videoId: "f3TkP0ZbMp8",
        title: "India Today Exclusive: Meghalaya CM Conrad Sangma Slams Media Trial In High-Profile Murder Case",
        description: "Description for Video 5",
        thumbnail: "https://i.ytimg.com/vi/f3TkP0ZbMp8/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDnGfHJur7OkryoZmAkHLqV0nIjWA",
        url: "https://www.youtube.com/watch?v=f3TkP0ZbMp8",
        profile: "https://yt3.ggpht.com/T2CFyCYOvSqnAJZL2HTDrLw-9Z48j97WXjHn41HoPXZ-ZaeH02WAFSBe2cDKRWNcjZR5lhtKcg=s88-c-k-c0x00ffffff-no-rj",
        channel: "Channel 5",
        channelId: "@channel5",
        banner: "https://yt3.googleusercontent.com/nJq0oT-z_xp-jouZtYoB0infUw--UBI1aSnWMGAgLIFjZauT7MOctf92GQDy5NYlRkBfiuQpRR4=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
        views: 5000,
        duration: "08:00",
        publishedAt: "2025-06-11",
        subscriberCount: 10000,
        category: ["Entertainment", "News"]
    },
    {
        id: 6,
        videoId: "TWM-atA8ft8",
        title: "Career Podcast || E1 - Content Creator || Code Freemen",
        description: "Description for Video 6",
        thumbnail: "https://i.ytimg.com/vi/TWM-atA8ft8/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBlWXgi3v86mpOgZtOSUyzVeRI20Q",
        url: "https://www.youtube.com/watch?v=TWM-atA8ft8",
        profile: "https://yt3.ggpht.com/kd_wAtpKhygpsXyZHGE5zDz2nM6dZmavS5WtCRHxy6VSZTAQY0UumPRSoZuj6EuYWaYnQ05C=s68-c-k-c0x00ffffff-no-rj",
        channel: "Channel 6",
        channelId: "@channel6",
        banner: "https://yt3.googleusercontent.com/arZJtHohCISyz3BrZA0ynNAM7rivDCBNwsDPtFI7p6SYswq5Tjhm783nGh1TOX4m4ksEV2sJ=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
        views: 6000,
        duration: "60:00",
        publishedAt: "2023-06-01",
        subscriberCount: 2000000,
        category: ["Podcast", "Career"]
    },
    {
        id: 7,
        videoId: "uBnTrlE5w1w",
        title: "Girish And The Chronicles Add A Rock 'N' Roll SPIN To Set Fire To The Rain by Adele | AGT 2025",
        description: "Description for Video 7",
        thumbnail: "https://i.ytimg.com/vi/uBnTrlE5w1w/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDUMPsrnoAivT_hdBCncXBGUGSo1Q",
        url: "https://www.youtube.com/watch?v=uBnTrlE5w1w",
        profile: "https://yt3.ggpht.com/0P-22oUtXljqqHyqrPUms4x0SMx5dDp_gPpwOc7TpibeN03ci7LkK-Thy_rAkieOpix1vRS5W28=s88-c-k-c0x00ffffff-no-rj",
        channel: "Channel 7",
        channelId: "@channel7",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: 7000,
        duration: "06:55",
        publishedAt: "2025-06-03",
        subscriberCount: 8792,
        category: ["Entertainment", "Music"]
    },
    {
        id: 8,
        videoId: "oPiEzDELhLI",
        title: "Linkin Park - 2025 UEFA Champions League Final Kick Off Show by Pepsi",
        description: "Description for Video 8",
        thumbnail: "https://i.ytimg.com/vi/oPiEzDELhLI/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDVwBXETow5uBzT2oiHaBdehAKy4g",
        url: "https://www.youtube.com/watch?v=oPiEzDELhLI",
        profile: "https://yt3.ggpht.com/OtUf050j6w6iRPUmGgmzblD2saluxUusxiVmo0-SMUnWiNKwR89JL_-xJ6JvIEram8UbPT_zDA=s88-c-k-c0x00ffffff-no-rj",
        channel: "Channel 8",
        channelId: "@channel8",
        banner: "https://yt3.googleusercontent.com/nJq0oT-z_xp-jouZtYoB0infUw--UBI1aSnWMGAgLIFjZauT7MOctf92GQDy5NYlRkBfiuQpRR4=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
        views: 8000,
        duration: "80:00",
        publishedAt: "2023-08-01",
        subscriberCount: 23002030,
        category: ["Entertainment", "Music"]
    },
    {
        id: 9,
        videoId: "pm-YNwjxfKU",
        title: "Portugal vs Spain | Final | Highlights | UEFA Nations League | 9th June 2025",
        description: "Description for Video 9",
        thumbnail: "https://i.ytimg.com/vi/pm-YNwjxfKU/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDXkWR--hDZyAC67vbxera494J19w",
        url: "https://www.youtube.com/watch?v=pm-YNwjxfKU",
        profile: "https://yt3.ggpht.com/6p7LTvjA8wmweYTfSZYsJ5kOOoDSsNj_6MZO2lIugeBM17i_244I-j-7fYZisHGiQEMLpgqoMA=s88-c-k-c0x00ffffff-no-rj",
        channel: "Channel 9",
        channelId: "@channel9",
        banner: "https://yt3.googleusercontent.com/arZJtHohCISyz3BrZA0ynNAM7rivDCBNwsDPtFI7p6SYswq5Tjhm783nGh1TOX4m4ksEV2sJ=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
        views: 9000,
        duration: "90:00",
        publishedAt: "2023-09-01",
        subscriberCount: 67657,
        category: ["Entertainment", "Sports"]
    },
    {
        id: 10,
        videoId: "Y_rFGDgvNOE",
        title: "12 Times Cristiano Ronaldo Became Portugal's Hero",
        description: "Description for Video 10",
        thumbnail: "https://i.ytimg.com/vi/Y_rFGDgvNOE/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDzm5oQT7RpQwyfvYV6yBCBeTwOvg",
        url: "https://www.youtube.com/watch?v=Y_rFGDgvNOE",
        profile: "https://yt3.ggpht.com/QM6PfOAcq61y4rjP3Xz0utt3vlh97JK4sWsgaS1jRPSeKmMNrwbV8pZ8GYPbUTxzwL7zUAgCpQ=s88-c-k-c0x00ffffff-no-rj",
        channel: "Channel 10",
        channelId: "@channel10",
        views: 10000,
        duration: "100:00",
        publishedAt: "2023-10-01",
        subscriberCount: 767112,
        category: ["Entertainment", "Sports"]
    },
    {
        id: 11,
        videoId: "GVcQfwFk-rg",
        title: "Ïa Ki Jingdon Jingem Ki Shikurim, Ki Nongtrei Manha Hotel Ki Ban Ïohi | Katkum Ka CCTV",
        description: "Description for Video 11",
        thumbnail: "https://i.ytimg.com/vi/GVcQfwFk-rg/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLC-eitqvV8IueauFSDwyWyr0m5M5A",
        url: "https://www.youtube.com/watch?v=GVcQfwFk-rg",
        profile: "https://yt3.ggpht.com/uzqjVPREImGM9v8N63I6sgpByD7WfVTBR6e4UKPrhEXLXGBB9dzOWHeLd30Ip2o4JQ96P22Tp2o=s88-c-k-c0x00ffffff-no-rj",
        channel: "Channel 11",
        channelId: "@channel11",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: 11000,
        duration: "110:00",
        publishedAt: "2023-11-01",
        subscriberCount: 548000,
        category: ["Entertainment", "News"]
    },
    {
        id: 12,
        videoId: "MZPS_9UB7Wg",
        title: "अरशद वारसी (Circuit) की सबसे सुपरहिट कॉमेडी मूवी सीन - हँस हँस कर पेट फुल जाएगा - Bollywood Cuts",
        description: "Description for Video 12",
        thumbnail: "https://i.ytimg.com/vi/4E2kY4YMsow/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLD5ypbs_HWCc_2gSg4xGT_mN7qnTQ",
        url: "https://www.youtube.com/watch?v=MZPS_9UB7Wg",
        profile: "https://yt3.ggpht.com/3z2Oaew8zrXEXqOkv7m-RzVBydnUkIFMIflxRrGn0st1UXUDyDVQALJZiqqPFSI5mxv7ec3Hfg=s88-c-k-c0x00ffffff-no-rj",
        channel: "Channel 12",
        channelId: "@channel12",
        banner: "https://yt3.googleusercontent.com/nJq0oT-z_xp-jouZtYoB0infUw--UBI1aSnWMGAgLIFjZauT7MOctf92GQDy5NYlRkBfiuQpRR4=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
        views: 12000,
        duration: "120:00",
        publishedAt: "2023-12-01",
        subscriberCount: 9998789,
        category: ["Entertainment", "Comedy", "Movies"]
    },
    {
        id: 13,
        videoId: "GnchzxXMMU8",
        title: "Best of Max Amini 2024 | Stand Up Comedy",
        description: "Description for Video 13",
        thumbnail: "https://i.ytimg.com/vi/GnchzxXMMU8/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLAIPsYAXSMhNd2gQzw0g7MRLykNBA",
        url: "https://www.youtube.com/watch?v=GnchzxXMMU8",
        profile: "https://yt3.ggpht.com/agEqZ08wJnRBAYVFJuIlF5Qdp_MHK-hQHA37B8vPASilp_LhF2KkkG3ckhzWh83kLdQPgNWYnw=s88-c-k-c0x00ffffff-no-rj",
        channel: "Channel 13",
        channelId: "@channel13",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: 3553043,
        duration: "130:00",
        publishedAt: "2023-01-02",
        subscriberCount: 2489483,
        category: ["Entertainment", "Comedy", "Movies"]
    },
    {
        id: 14,
        videoId: "HuGAY-jxMqs",
        title: "Miracle Survivor, Ramesh, Found In Air India Plane Crash, Jumped From Seat 11A | Ahmedabad Crash",
        description: "Description for Video 14",
        thumbnail: "https://i.ytimg.com/vi/HuGAY-jxMqs/hqdefault.jpg?sqp=-oaymwEnCOADEI4CSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLC6ihmor9IweJwcbsC-0OMvqB5fwA",
        url: "https://www.youtube.com/watch?v=HuGAY-jxMqs",
        profile: "https://yt3.ggpht.com/T2CFyCYOvSqnAJZL2HTDrLw-9Z48j97WXjHn41HoPXZ-ZaeH02WAFSBe2cDKRWNcjZR5lhtKcg=s88-c-k-c0x00ffffff-no-rj",
        channel: "Channel 14",
        channelId: "@channel14",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: 638252,
        duration: "05:23",
        publishedAt: "2025-05-12",
        subscriberCount: 2489483,
        category: ["News"]
    },
    {
        id: 15,
        videoId: "oQU3UQ4WLnQ",
        title: "8 Times SHELDON Went TOO FAR!!! - The Big Bang Theory",
        description: "Description for Video 15",
        thumbnail: "https://i.ytimg.com/vi/oQU3UQ4WLnQ/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLB837fF17d6QBhpvoYgdBGDswNrNw",
        url: "https://www.youtube.com/watch?v=oQU3UQ4WLnQ",
        profile: "https://yt3.ggpht.com/ytc/AIdro_kYiBYf_eBnPaUYyBbGf8T6aK8fGQGWjYWwEGrbG4wDGxQ=s88-c-k-c0x00ffffff-no-rj",
        channel: "Channel 14",
        channelId: "@channel14",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: 3494582,
        duration: "05:23",
        publishedAt: "2024-09-12",
        subscriberCount: 2489483,
        category: ["Entertainment", "Comedy", "Movies"]
    },
    {
        id: 16,
        videoId: "cezuaA6nZ48",
        title: "The Ones with Joey the Ladies' Man | Friends",
        description: "Description for Video 16",
        thumbnail: "https://i.ytimg.com/vi/cezuaA6nZ48/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBMtKkUM4OYWUs90c51nZWrFM-Pdg",
        url: "https://www.youtube.com/watch?v=cezuaA6nZ48",
        profile: "https://yt3.ggpht.com/3zLX8BeOwwtz1MkINGqipfUXnxbClOn6y0Kls4KeIou4m7s17I4O6dApeY_RbfuBocK1qMsTpA=s88-c-k-c0x00ffffff-no-rj",
        channel: "Channel 16",
        channelId: "@channel16",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: 2872328,
        duration: "19:57",
        publishedAt: "2025-04-10",
        subscriberCount: 979341,
        category: ["Entertainment", "Comedy", "Movies"]
    },
    {
        id: 17,
        videoId: "a-HPQoNNjsk",
        title: "The Weeknd and Jimmy Crash a College Graduation Party and Perform Blinding Lights/Can’t Feel My Face",
        description: "Description for Video 17",
        thumbnail: "https://i.ytimg.com/vi/a-HPQoNNjsk/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDmMM27-au01et12h94BfyFecekhA",
        url: "https://www.youtube.com/watch?v=a-HPQoNNjsk",
        profile: "https://yt3.ggpht.com/rNNmF5XK6SpfwhSL2Uf-GFiezejcbhfRYax6qTG0wQNHbBldm3YyQ6HLY6Ps4YweUNvXQGvUCg=s88-c-k-c0x00ffffff-no-rj",
        channel: "Channel 16",
        channelId: "@channel16",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: 592892,
        duration: "04:08",
        publishedAt: "2025-05-22",
        subscriberCount: 32482934,
        category: ["Entertainment", "Comedy", "Music"]
    },
    {
        id: 18,
        videoId: "FtTjES3Ywcw",
        title: "Khmih-Sohra & Nongstoiñ |Asian Cup Qualifiers |Rendition of Ri Lum & Maa tujhe salaam |Vande Mataram",
        description: "Description for Video 18",
        thumbnail: "https://i.ytimg.com/vi/FtTjES3Ywcw/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOG1xRHLjrMmoM6FzqiJN2TdDSPQ",
        url: "https://www.youtube.com/watch?v=FtTjES3Ywcw",
        profile: "https://yt3.ggpht.com/ytc/AIdro_ktajJ6fqqpf29h5gVDW14rIDDlzYGrXD0iJ0riH9Fl-A=s88-c-k-c0x00ffffff-no-rj",
        channel: "Channel 18",
        channelId: "@channel18",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: 1873827,
        duration: "03:29",
        publishedAt: "2025-04-10",
        subscriberCount: 77876,
        category: ["Entertainment", "Sports", "Music"]
    },
    {
        id: 19,
        videoId: "uZbXOmWVkb8",
        title: "Dirk After Dark Part 2 - Last War : Survivor - Dirk Diggler - Live Game Play",
        description: "Description for Video 19",
        thumbnail: "https://i.ytimg.com/vi/uZbXOmWVkb8/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCn5reJwavK69H4V3OzbH0AVDzfVA",
        url: "https://www.youtube.com/watch?v=uZbXOmWVkb8",
        profile: "https://yt3.ggpht.com/gvhq7pLT_DTy848zFOogiMK0PGUQRIfGEPPz-CmbRu-d0vnPyNhNCllVJ04rfSP0mRP1Iyr2=s88-c-k-c0x00ffffff-no-rj",
        channel: "Channel 19",
        channelId: "@channel19",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: 1873827,
        duration: "120:17",
        publishedAt: "2025-06-12",
        subscriberCount: 535473,
        category: ["Entertainment", "Gaming"]
    },
    {
        id: 20,
        videoId: "a6ZQ_PRxiKg",
        title: "Last War Survival: **UPDATED** Skill Chip Guide",
        description: "Description for Video 20",
        thumbnail: "https://i.ytimg.com/vi/a6ZQ_PRxiKg/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBLLsDT1-yiEQHmIZHqj67nkc2YYQ",
        url: "https://www.youtube.com/watch?v=a6ZQ_PRxiKg",
        profile: "https://yt3.ggpht.com/ytc/AIdro_kgeb3tvIBGrdY-IdjHykSG-MSKpwcehWUAO3_O6TXPgadO46BAk4RkoG8qNgXDJBfHxg=s88-c-k-c0x00ffffff-no-rj",
        channel: "Channel 20",
        channelId: "@channel20",
        banner: 'https://yt3.googleusercontent.com/icWhzJbfwy69L7We9WUcYtf9up6WF9VWsrLku_oJBzDg0qaNUrRFSSTsV9Ms0XTZjmK59TD4W54=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj',
        views: 2587,
        duration: "12:17",
        publishedAt: "2025-05-12",
        subscriberCount: 1243,
        category: ["Entertainment", "Gaming"]
    }
]